# Generated by Django 5.0.2 on 2024-02-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes'),
        ),
    ]
